=== lexml/lexml-xml-schemas/src/main/resources/xsd/lexml-emenda-proposicao.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema targetNamespace="http://www.lexml.gov.br/lexml-emenda-proposicao/1.0" xmlns="http://www.lexml.gov.br/lexml-emenda-proposicao/1.0"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  elementFormDefault="qualified">

  <xsd:redefine schemaLocation="lexml-base.xsd" />

  <xsd:element name="EmendaProposicao">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="MetadadoEmenda"></xsd:element>
        <xsd:element ref="Emenda"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="MetadadoEmenda">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Propriedades"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Emenda">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Proposicao">
          <xsd:complexType>
            <xsd:simpleContent>
              <xsd:extension base="xsd:string">
                <xsd:attribute name="URN" type="xsd:anyURI" />
              </xsd:extension>
            </xsd:simpleContent>
          </xsd:complexType>
        </xsd:element>
        <xsd:element ref="Marcadores" />
        <xsd:element ref="Justificativa" />
        <xsd:element ref="ComandoEmenda" minOccurs="0" maxOccurs="1" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Propriedades">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Descricao" type="xsd:string"></xsd:element>
        <xsd:element name="Elaborador" type="xsd:string"></xsd:element>
        <xsd:element name="Concluida" type="xsd:string"></xsd:element>
        <xsd:element name="Observacao" type="xsd:string"></xsd:element>
        <xsd:element name="Situacao" type="xsd:string"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="URN">
    <xsd:complexType>
      <xsd:attribute name="href" type="xsd:string"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Marcadores">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="DispositivosImportados"></xsd:element>
        <xsd:element ref="DispositivosSuprimidos"></xsd:element>
        <xsd:element ref="DispositivosModificados"></xsd:element>
        <xsd:element ref="DispositivosAdicionados"></xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Justificativa">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="p" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID"></xsd:attribute>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="DispositivosImportados" type="xsd:string"></xsd:element>

  <xsd:element name="DispositivosSuprimidos">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Supressao" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="DispositivosModificados">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Modificacao" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="DispositivosAdicionados">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Adicao" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Supressao">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:group ref="Dispositivos" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID" />
      <xsd:attribute name="parteProposicao" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Modificacao">
    <xsd:complexType>
      <xsd:choice>
        <xsd:element ref="Ementa" />
        <xsd:element ref="Preambulo" />
        <xsd:group ref="Dispositivos" />
      </xsd:choice>
      <xsd:attribute name="id" type="xsd:ID" />
      <xsd:attribute name="parteProposicao" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Adicao">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:group ref="Dispositivos" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID" />
      <xsd:attribute name="parteProposicao" type="xsd:string" />
      <xsd:attribute name="refidPai" type="xsd:string" use="optional" />
      <xsd:attribute name="refidIrmao" type="xsd:string" use="optional" />
      <xsd:attribute name="posicaoAdicao" type="PosicaoAdicaoType" use="optional" />
    </xsd:complexType>
  </xsd:element>

  <!-- Dispositivos -->

  <xsd:group name="Dispositivos">
    <xsd:choice>
      <xsd:element ref="Parte" />
      <xsd:element ref="Livro" />
      <xsd:element ref="Titulo" />
      <xsd:element ref="Capitulo" />
      <xsd:element ref="Secao" />
      <xsd:element ref="Subsecao" />
      <xsd:element ref="Artigo" />
      <xsd:element ref="Caput" />
      <xsd:element ref="Paragrafo" />
      <xsd:element ref="Inciso" />
      <xsd:element ref="Alinea" />
      <xsd:element ref="Item" />
    </xsd:choice>
  </xsd:group>

  <xsd:complexType name="AgrupadorType">
    <xsd:sequence>
      <xsd:element ref="Rotulo" minOccurs="0" maxOccurs="1" />
      <xsd:element ref="NomeAgrupador" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" />
  </xsd:complexType>

  <xsd:element name="Parte" type="AgrupadorType" />

  <xsd:element name="Livro" type="AgrupadorType" />

  <xsd:element name="Titulo" type="AgrupadorType" />

  <xsd:element name="Capitulo" type="AgrupadorType" />

  <xsd:element name="Secao" type="AgrupadorType" />

  <xsd:element name="Subsecao" type="AgrupadorType" />

  <xsd:element name="Artigo">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="TituloDispositivo" minOccurs="0" maxOccurs="1" />
        <xsd:element ref="Rotulo" minOccurs="0" maxOccurs="1" />
        <xsd:element ref="p" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="Alteracao" minOccurs="0" maxOccurs="1" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID" />
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Caput">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="p" minOccurs="0" maxOccurs="unbounded" />
        <xsd:element ref="Alteracao" minOccurs="0" maxOccurs="1" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="OutrosDispositivosType">
    <xsd:sequence>
      <xsd:element ref="TituloDispositivo" minOccurs="0" maxOccurs="1" />
      <xsd:element ref="Rotulo" minOccurs="0" maxOccurs="1" />
      <xsd:element ref="p" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element ref="Alteracao" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" />
  </xsd:complexType>

  <xsd:element name="Paragrafo" type="OutrosDispositivosType" />

  <xsd:element name="Inciso" type="OutrosDispositivosType" />

  <xsd:element name="Alinea" type="OutrosDispositivosType" />

  <xsd:element name="Item" type="OutrosDispositivosType" />

  <!-- Comando de emenda -->

  <xsd:element name="ComandoEmenda">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="p" minOccurs="0" maxOccurs="1" />
        <xsd:element name="Citacao" type="CitacaoCEType" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID" />
      <xsd:attribute name="tipoComando" type="TipoComandoType" />
      <xsd:attribute name="acaoComando" type="AcaoComandoType" />
      <xsd:attribute name="refIdsSupressao" type="xsd:IDREFS" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="CitacaoCEType" mixed="true">
    <xsd:sequence>
      <xsd:choice>
        <xsd:group ref="HierCitacaoCEType" />
        <xsd:element name="Aspas">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:group ref="HierCitacaoCEType" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:choice>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:group name="HierCitacaoCEType">
    <xsd:choice>
      <xsd:choice>
        <xsd:element name="Artigo" type="ArtigoCEType" />
        <xsd:element name="Caput" type="CaputCEType" />
        <xsd:element name="Paragrafo" type="ParagrafoCEType" />
        <xsd:element name="Inciso" type="IncisoCEType" />
        <xsd:element name="Alinea" type="AlineaCEType" />
        <xsd:element name="Item" type="ItemCEType" />
      </xsd:choice>
    </xsd:choice>
  </xsd:group>

  <xsd:complexType name="ArtigoCEType">
    <xsd:sequence>
      <xsd:element ref="Rotulo" minOccurs="0" maxOccurs="1" />
      <xsd:element name="Caput" type="CaputCEType" minOccurs="0" maxOccurs="1" />
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="Paragrafo" type="ParagrafoCEType" />
        <xsd:element name="Omissis" type="OmissisCEType" />
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="refid" type="xsd:IDREF" use="optional" />
  </xsd:complexType>

  <xsd:complexType name="CaputCEType">
    <xsd:sequence>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="Inciso" type="IncisoCEType" />
        <xsd:element name="Omissis" type="OmissisCEType" />
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="refid" type="xsd:IDREF" use="optional" />
  </xsd:complexType>

  <xsd:complexType name="ParagrafoCEType">
    <xsd:sequence>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="Inciso" type="IncisoCEType" />
        <xsd:element name="Omissis" type="OmissisCEType" />
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="refid" type="xsd:IDREF" use="optional" />
  </xsd:complexType>

  <xsd:complexType name="IncisoCEType">
    <xsd:sequence>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="Alinea" type="AlineaCEType" />
        <xsd:element name="Omissis" type="OmissisCEType" />
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="refid" type="xsd:IDREF" use="optional" />
  </xsd:complexType>

  <xsd:complexType name="AlineaCEType">
    <xsd:sequence>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="Item" type="ItemCEType" />
        <xsd:element name="Omissis" type="OmissisCEType" />
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="refid" type="xsd:IDREF" use="optional" />
  </xsd:complexType>

  <xsd:complexType name="ItemCEType">
    <xsd:attribute name="refid" type="xsd:IDREF" use="optional" />
  </xsd:complexType>

  <xsd:complexType name="OmissisCEType">
    <xsd:sequence>
      <xsd:element ref="Rotulo" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>

  <!-- Enumerações -->

  <xsd:simpleType name="TipoComandoType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="agrupador" />
      <xsd:enumeration value="simples" />
      <xsd:enumeration value="complexo" />
      <xsd:enumeration value="artigoTodo" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="AcaoComandoType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="adicao" />
      <xsd:enumeration value="supressao" />
      <xsd:enumeration value="alteracao" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="PosicaoAdicaoType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="anterior" />
      <xsd:enumeration value="posterior" />
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== lexml/lexml-xml-schemas/src/test/xml/emenda/corretos/emenda1.xml
<?xml version="1.0" encoding="UTF-8"?>
<EmendaProposicao xmlns="http://www.lexml.gov.br/lexml-emenda-proposicao/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.lexml.gov.br/lexml-emenda-proposicao/1.0 ../xsd/lexml-emenda-proposicao.xsd">
  <MetadadoEmenda>
    <Propriedades>
      <Descricao></Descricao>
      <Elaborador>fragomeni</Elaborador>
      <Concluida>0</Concluida>
      <Observacao></Observacao>
      <Situacao>Emenda Inv√°lida</Situacao>
    </Propriedades>
  </MetadadoEmenda>
  <Emenda id='emd'>
    <Proposicao URN='urn:lex:br:congresso.nacional:medida.provisoria:2005-04-04;244:@200504040101'>MPV 244/2005</Proposicao>
    <Marcadores>
      <DispositivosImportados></DispositivosImportados>
      <DispositivosSuprimidos></DispositivosSuprimidos>
      <DispositivosModificados></DispositivosModificados>
      <DispositivosAdicionados>
        <Adicao id='adi1' parteProposicao='Texto' refidPai="art1_cpt">
          <Inciso id="art1_cpt_inc1">
            <Rotulo>I -</Rotulo>
            <p> kkkkkk </p>
          </Inciso>
        </Adicao>
      </DispositivosAdicionados>
    </Marcadores>
    <Justificativa id='emd1_jus'>
    </Justificativa>
    <ComandoEmenda id="emd_cmd1" tipoComando="simples" acaoComando="alteracao"></ComandoEmenda>
  </Emenda>
</EmendaProposicao>

=== lexml/lexml-xml-schemas/src/test/xml/emenda/corretos/varias supressoes.xml
<?xml version="1.0" encoding="UTF-8"?>
<EmendaProposicao xmlns="http://www.lexml.gov.br/lexml-emenda-proposicao/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.lexml.gov.br/lexml-emenda-proposicao/1.0 ../xsd/lexml-emenda-proposicao.xsd">
  <MetadadoEmenda>
    <Propriedades>
      <Descricao></Descricao>
      <Elaborador>jholanda</Elaborador>
      <Concluida>0</Concluida>
      <Observacao></Observacao>
      <Situacao>Emenda Inválida</Situacao>
    </Propriedades>
  </MetadadoEmenda>
  <Emenda id='emd'>
    <Proposicao URN='urn:lex:br:congresso.nacional:medida.provisoria:2005-04-04;244:@200504040101'>MPV 244/2005</Proposicao>
    <Marcadores>
      <DispositivosImportados></DispositivosImportados>
      <DispositivosSuprimidos>
        <Supressao id='sup1' parteProposicao='Texto'>
          <Artigo id='art1'>
            <Rotulo>Art. 1º</Rotulo>
          </Artigo>
        </Supressao>
        <Supressao id='sup2' parteProposicao='Texto'>
          <Inciso id='art2_cpt_inc4'>
            <Rotulo>IV -</Rotulo>
          </Inciso>
        </Supressao>
        <Supressao id='sup3' parteProposicao='Texto'>
          <Inciso id='art2_cpt_inc5'>
            <Rotulo>V -</Rotulo>
          </Inciso>
        </Supressao>
        <Supressao id='sup4' parteProposicao='Texto'>
          <Inciso id='art2_cpt_inc11'>
            <Rotulo>XI -</Rotulo>
          </Inciso>
        </Supressao>
        <Supressao id='sup5' parteProposicao='Texto'>
          <Artigo id='art3'>
            <Rotulo>Art. 3º</Rotulo>
          </Artigo>
        </Supressao>
      </DispositivosSuprimidos>
      <DispositivosModificados></DispositivosModificados>
      <DispositivosAdicionados></DispositivosAdicionados>
    </Marcadores>
    <Justificativa id='emd1_jus'>
    </Justificativa>
    <ComandoEmenda id="emd_cmd1" tipoComando="artigoTodo" acaoComando="supressao" refIdsSupressao="sup1 sup3 sup5">
        <p>Suprimam-se o Art. 1º, os incisos IV, V e XI do caput do Art. 2º e o Art. 3º</p>
    </ComandoEmenda>
  </Emenda>
</EmendaProposicao>

=== lexml/lexml-xml-schemas/src/test/xml/emenda/corretos/um artigo no meio.xml
<?xml version="1.0" encoding="UTF-8"?>
<EmendaProposicao xmlns="http://www.lexml.gov.br/lexml-emenda-proposicao/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.lexml.gov.br/lexml-emenda-proposicao/1.0 ../xsd/lexml-emenda-proposicao.xsd">
  <MetadadoEmenda>
    <Propriedades>
      <Descricao></Descricao>
      <Elaborador>jholanda</Elaborador>
      <Concluida>0</Concluida>
      <Observacao></Observacao>
      <Situacao>Emenda Inválida</Situacao>
    </Propriedades>
  </MetadadoEmenda>
  <Emenda id='emd'>
    <Proposicao URN='urn:lex:br:congresso.nacional:medida.provisoria:2005-04-04;244:@200504040101'>MPV 244/2005</Proposicao>
    <Marcadores>
      <DispositivosImportados></DispositivosImportados>
      <DispositivosSuprimidos></DispositivosSuprimidos>
      <DispositivosModificados></DispositivosModificados>
      <DispositivosAdicionados>
        <Adicao id='adi1' parteProposicao='Texto' refidIrmao="art1" posicaoAdicao="posterior">
          <Artigo id="art1-A">
            <Rotulo>Art. 1º-A</Rotulo>
          </Artigo>
        </Adicao>
        <Adicao id='adi2' parteProposicao='Texto' refidPai="art1-A">
          <Caput id="art1-A_cpt">
              <p> asdsadsadsa </p>
          </Caput>
        </Adicao>
      </DispositivosAdicionados>
    </Marcadores>
    <Justificativa id='emd1_jus'></Justificativa>
    <ComandoEmenda id="emd_cmd1" tipoComando="complexo" acaoComando="adicao">
        <p>Acrescente-se após o Art. 1º o seguinte artigo:</p>
        <Citacao>
          <Aspas>
            <Artigo refid='adi1'>
              <Caput refid='adi2'></Caput>
            </Artigo>
          </Aspas>
        </Citacao>
    </ComandoEmenda>
  </Emenda>
</EmendaProposicao>
